# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DJDX7cEGJKmPA_hF0HjQgMtQz9dhb6S
"""

# import the "array" for demonstrating array operations
import array
#initializing an array with array values and signed integers
arr = array.array("I",[3,6,9,12,15,18])

# print the original array
print("New created array:",end="")
for I in range(0,5):
  print(arr[I],end="")
  print("\r")

import pandas as pd

dict = {'name':["Parveen","Khushi","Sukh","Karan"],
'age': ["17","18","19","14"]}
info = pd.DataFrame(dict,index=[True,False,True,True])
print(info)

import pandas as pd
dict = {'name': ["Jass","Arjot","Armaan","Mann"],
'age':["36","11","11","21"]}
info = pd.DataFrame(dict,index= [True,False,True,True])
print(info.loc[True])

import numpy as np
arr = np.arange(14)
print("The Original array is:\n",arr)
arr =  np.arange(14).reshape(2,7)
print("\nreshaped array:\n",arr)
arr = np.arange(14).reshape(7,2)
print("\nreshaped array:\n",arr)

