# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJXlwoH3A80u_DABrk3NRUPzH5lnUUM7
"""

import pandas as pd
import numpy as np

info = np.array(['P','a','n','d','a','s'])
a = pd.Series(info)
print(a)

info = np.array(['P','a','r','v','e','e','n'])
a = pd.Series(info)
print(a)

# a list of strings
x = ['Python','Pandas']

# Calling DataFrame costructor on list
df = pd.DataFrame(x)
print(df)

from re import X
# a list of strings
x = ['Parveen','Aulakh']

# Calling DataFrame constructor on list
df = pd.DataFrame(x)
print(df)

import numpy as np
a = pd.Series(['Java','OOPs','Python',np.nan])
a.map({'Python':'Main', 'OOPs':'Core'})

import matplotlib.pyplot as pit
import pandas as pd

Emp = ['Parker','John','Smith','William']
ID = [102,107,109,114]
emp_series = pd.Series(Emp)
id_series = pd.Series(ID)
frame = {'Emp': emp_series,'ID': id_series}
result = pd.DataFrame(frame)
print(result)

